<footer class="footer">
    <div class="container">
        <p class="pull-left">Thanks to all contributors and to <a href="https://github.com/Team-Sass">Team-Sass</a> for their support.</p>
        <ul class="pull-right  list-unstyled">
            <li class="pull-left"><a href="https://twitter.com/hugogiraudel">@HugoGiraudel</a></li>
            <li class="pull-left"><a href="https://github.com/Team-Sass/SassyLists">GitHub</a></li>
        </ul>
    </div>
</footer>